### ISSUE TITLE
Error including sorc autobuild template

### ISSUE THREAD

**Issue by hunzhang** [Adpist/horde#85]
Sorc is always trying to include the autobuild template file "config/Builds/Sorceress.HammerConviction.js" which doesn't exist.
![error](https://user-images.githubusercontent.com/7600910/104934998-aa088500-59e5-11eb-9dcb-18c1ef11beb3.png)

**Comment by Adpist** [comment]
what build is set to your character in the team file ?

**Comment by hunzhang** [comment]
> what build is set to your character in the team file ?

I set the 2 sorcs using "cold" build type.

**Comment by Adpist** [comment]
Can you try after changing one of the two sorc build ? Also probably stupid question, but are you up to date ?

**Comment by hunzhang** [comment]
> Can you try after changing one of the two sorc build ? Also probably stupid question, but are you up to date ?

Tried change the other sorc to 'fire' build but the two sorcs had the same problem. Pally and Barb works well. Bot is up to date. Now trying removing the '-' from char name.

**Comment by Adpist** [comment]
Well i though i fixed this a while ago :/

i don't have time to work on horde for now i'm sorry. If you need to level chars you shouldn't pick same elements for your sorcs, it will slow the process. You can always respec it once levelled.

**Comment by hunzhang** [comment]
> Well i though i fixed this a while ago :/
> 
> i don't have time to work on horde for now i'm sorry. If you need to level chars you shouldn't pick same elements for your sorcs, it will slow the process. You can always respec it once levelled.

Thank you for the great work.
