### ISSUE TITLE
How to set the leader Election? 

### ISSUE THREAD

**Issue by ircopdd** [Adpist/horde#86]
I only found this
"teleport", "bo", "follower"

**Comment by Adpist** [comment]
teleport is the leader.

**Comment by ircopdd** [comment]
> teleport is the leader.

I set 1 teleport and 1 follower and have been waiting for leader Election

**Comment by Adpist** [comment]
Do you have only 2 entries in your team file (remove extra chars if they are not present)

**Comment by ircopdd** [comment]
ㄒ

> 您的團隊文件中只有2個條目嗎（如果不存在多餘的字符，請刪除它們）

Thank you is work
