### ISSUE TITLE
Error in Horde (sequencer.js #222) sequences is not an object (Area: 1, Ping:78, Game: )

### ISSUE THREAD

**Issue by VengeanceVIP** [Adpist/horde#94]
Getting this error constantly and have no idea what to do, i've set up my team, done all the config and this is what i get after it tries to start

This is line 222 if sequencer file, 		var sequencesList = Object.keys(sequences);

Any help would be appreciated :) im on the latest download

FIXED: Did not set up my trapsin properly.

**Comment by Adpist** [comment]
Usually this error means there is an error somewhere on the overall team setup as you noticed :)
